### ISSUE TITLE
Crash, when SENZING_UID is set via an environment variable

### ISSUE THREAD

**Issue by ivanRylach** [Senzing/docker-init-container#18]
**Describe the bug**
`init-contianer.py` script crashes. when SENZING_UID is provided via environment variable.

**To Reproduce**

1. `export SENZING_UID=1001`
2. `/app/init-container.py initialize`
3. See error

**Expected behavior**
Script executes successfully.

**Trace**
```
2019-11-01 21:46:01,623 senzing-50070297I Enter {"config_path": "/etc/opt/senzing", "debug": false, "etc_dir": "/app/opt/senzing", "etc_template_dir": "/etc/opt/senzing", "g2_database_url": "", "g2_database_url_raw": "", "g2_dir": "/opt/senzing/g2", "gid": "1001", "init_container_sleep": 0, "resource_path": "/opt/senzing/g2/resources", "sleep_time_in_seconds": 0, "start_time": 1572644761.6237478, "subcommand": "initialize", "support_path": "/opt/senzing/data", "uid": "1001", "var_dir": "/app/var/senzing"}
...
Traceback (most recent call last):
  File "/app/init-container.py", line 1273, in <module>
    globals()[subcommand_function_name](args)
  File "/app/init-container.py", line 1137, in do_initialize
    change_file_permissions(config)
  File "/app/init-container.py", line 774, in change_file_permissions
    os.chown(filename, requested_file_uid, requested_file_gid)
TypeError: uid should be integer, not str
```

**Comment by docktermj** [comment]
@ivanRylach A new `senzing/init-container:1.3.2` (or `:latest`) with the fix is now available on DockerHub (https://hub.docker.com/r/senzing/init-container).  As you probably know, do a
```
sudo docker pull senzing/init-container
```
to get the new docker image.

If you are satisfied with the fix, feel free to close the issue.   If I don't hear from you in a week or so, I'll close the issue.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-init-container/pull/19
2. https://github.com/Senzing/docker-init-container/pull/20
